apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["/bin/bash", "-c"]
    args: ["apt update && apt install -y curl iputils-ping && sleep infinity"]
    #args:
    #- sleep
    #- infinity
