apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: true
  pairs:
    app: ejemplo
    
resources:
- 15-pod-secret.yaml

secretGenerator:
- literals:
  - username=admin
  - password=password!!
  name: db-credentials

images:
- name: nginx
  newTag: latest

